name: Daily Blocker Scan
on:
  schedule:
    - cron: '15 9 * * *'   # 09:15 UTC, adjust in Governance.md
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Placeholder
        run: echo "Blocker scan stub – to be implemented"
