name: Fact Impact Scan
on:
  push:
    paths:
      - 'FactLog.md'
  workflow_dispatch:

jobs:
  impact:
    runs-on: ubuntu-latest
    steps:
      - name: Placeholder
        run: echo "Fact impact scan stub – to be implemented"
