name: GPT-CMD Processor

on:
  push:
    branches:
      - main

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Extract directive from commit message
        shell: bash
        run: |
          msg=$(git log -1 --pretty=%B)
          echo "$msg" | sed -n '/^GPT-CMD_DIRECTIVE:/,$p' | sed '1d' > /tmp/directive.json

      - name: Debug directive
        shell: bash
        run: |
          echo "--- directive.json ---"
          cat /tmp/directive.json

      - name: Run parser
        shell: bash
        run: |
          python3 scripts/parse_gpt_cmd.py < /tmp/directive.json
