name: GPT-CMD Processor

on:
  push:
    branches: [ main ]
    paths:
      - '.gptcmd/directive.json'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Parser
        run: python3 scripts/parse_gpt_cmd.py < .gptcmd/directive.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Clean up directive file
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git rm .gptcmd/directive.json
          git commit -m "GPT-CMD: Remove processed directive"
          git push origin main
