name: GPT-CMD Processor

permissions:
  contents: write   # <-- allows push via the default GITHUB_TOKEN


on:
  push:
    branches:
      - main

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Extract directive from commit message
        shell: bash
        run: |
          msg=$(git log -1 --pretty=%B)
          echo "$msg" | sed -n '/^GPT-CMD_DIRECTIVE:/,$p' | sed '1d' > /tmp/directive.json

      - name: Debug directive
        shell: bash
        run: |
          echo "--- directive.json ---"
          cat /tmp/directive.json

      - name: Run parser
        shell: bash
        run: |
          python3 scripts/parse_gpt_cmd.py < /tmp/directive.json

      - name: Commit and push changes
        shell: bash
        run: |
          if git status --porcelain | grep -q .; then
            git config user.name "gpt-cmd-bot"
            git config user.email "bot@users.noreply.github.com"
            git add -A
            git commit -m "Apply GPT-CMD directive"
            git push origin HEAD:main
          else
            echo "No changes produced by directive." >&2
            exit 1   # fail-fast rule
          fi

