name: GPT-CMD Processor

on:
  workflow_dispatch:
  issue_comment:
    types: [created]

jobs:
  process-gptcmd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Run GPT-CMD Parser
        run: python scripts/parse_gpt_cmd.py
