name: Daily Progress Summary
on:
  schedule:
    - cron: '0 9 * * *'    # 09:00 UTC
  workflow_dispatch:

jobs:
  summary:
    runs-on: ubuntu-latest
    steps:
      - name: Placeholder
        run: echo "Summary stub – to be implemented"
