# .github/workflows/summary.yml
name: Daily Summary

on:
  schedule:
    - cron: '0 6 * * *'   # 09:00 Europe/Istanbul

jobs:
  daily-summary:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate daily summary (placeholder)
        run: echo "Summary logic to be implemented"
